repos:
- repo: local
  hooks:
    - id: lint-and-pytest
      name: Run linter and pytest for python-fastapi-asyncpg
      entry: bash -c 'cd python-fastapi-asyncpg/ && make lint && make test'
      language: system
      pass_filenames: false
    - id: go-formatter
      name: Run formatter for golang-gin-pgx
      entry: bash -c 'cd golang-gin-pgx/ && make format'
      language: system
      pass_filenames: false
