repos:
- repo: local
  hooks:
    - id: lint-pytest-loadtest
      name: Run linter, pytest, and loadtest for python-fastapi-asyncpg
      entry: bash -c 'cd python-fastapi-asyncpg/ && make pre-commit'
      language: system
      pass_filenames: false
    - id: go-formatter
      name: Run formatter for golang-gin-pgx
      entry: bash -c 'cd golang-gin-pgx/ && make format'
      language: system
      pass_filenames: false
