definitions:
  main.statusResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /status:
    get:
      description: returns "ok!" if server is up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.statusResponse'
      summary: status endpoint
      tags:
      - status
swagger: "2.0"
